# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  # We make important mistakes fatal so that the project doesn't end up as garbage.
  errors:
    todo: ignore
    unused_local_variable: error
    unused_import: error
    invalid_annotation_target: ignore
    use_build_context_synchronously: error # This is the base for Flutter.
  exclude:
    - "bin/cache/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart" # We exclude code generation
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # --- SECURITY AND BUGS (What really crashes the prod) ---
    - cancel_subscriptions        # Forgot to unsubscribe to dispose? Get a leak.
    - close_sinks                 # Streams need to be closed.
    - unawaited_futures           # You're not expecting the future? That means you don't control the flow.
    - avoid_slow_async_io         # File I/O in asynchronous code must be fast.
    - throw_in_finally            # Throwing errors in finally is architectural suicide.

    # --- STYLE AND PURE ARCHITECTURE ---
    - always_declare_return_types # developer always writes what the function returns.
    - prefer_final_locals         # Immutability is the key to no bugs.
    - prefer_final_fields         # Class fields must be final unless they are state.
    - avoid_relative_lib_imports  # Package imports ONLY. No ../../../
    - cascade_invocations         # Cleaner code when working with a single object.
    - directives_ordering         # Order in imports = order in your head.

    # --- FLUTTER RULES ---
    - prefer_const_constructors             # We save FPS, help the engine.
    - prefer_const_declarations             # Constants instead of final where possible.
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace              # Don't use Container where you just need indentation.
    - use_key_in_widget_constructors        # The basis for the widget tree.

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
