// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:collab_tasks/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4d49OXmkpJrJ124HGFAYPtXn8BsvbyY',
    appId: '1:266279169943:web:01a574649f47c909485ed2',
    messagingSenderId: '266279169943',
    projectId: 'collabtasks-fda3f',
    authDomain: 'collabtasks-fda3f.firebaseapp.com',
    storageBucket: 'collabtasks-fda3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctNefsmn8z41vz9rcM31iICFC_GbXT7g',
    appId: '1:266279169943:android:b1a0ac60d881d40f485ed2',
    messagingSenderId: '266279169943',
    projectId: 'collabtasks-fda3f',
    storageBucket: 'collabtasks-fda3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbppatsG1roAQpa-aawcX9Cj58J1AQx0',
    appId: '1:266279169943:ios:94ad95be32fce93c485ed2',
    messagingSenderId: '266279169943',
    projectId: 'collabtasks-fda3f',
    storageBucket: 'collabtasks-fda3f.firebasestorage.app',
    androidClientId: '266279169943-p6ugd9bc7356tare58m2k5qhhbb1okvk.apps.googleusercontent.com',
    iosClientId: '266279169943-det05u6phg7ijca97p9t2bkd9modffri.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbppatsG1roAQpa-aawcX9Cj58J1AQx0',
    appId: '1:266279169943:ios:94ad95be32fce93c485ed2',
    messagingSenderId: '266279169943',
    projectId: 'collabtasks-fda3f',
    storageBucket: 'collabtasks-fda3f.firebasestorage.app',
    androidClientId: '266279169943-p6ugd9bc7356tare58m2k5qhhbb1okvk.apps.googleusercontent.com',
    iosClientId: '266279169943-det05u6phg7ijca97p9t2bkd9modffri.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP4d49OXmkpJrJ124HGFAYPtXn8BsvbyY',
    appId: '1:266279169943:web:a07f0f5e2ec0f1b1485ed2',
    messagingSenderId: '266279169943',
    projectId: 'collabtasks-fda3f',
    authDomain: 'collabtasks-fda3f.firebaseapp.com',
    storageBucket: 'collabtasks-fda3f.firebasestorage.app',
  );
}
